/**** C2 / C1 example-chip export  (Supplementary figure, step 2 -- GEE path) ****
 *
 * Paste into the GEE Code Editor (code.earthengine.google.com) and Run.
 *
 * Produces one Sentinel-2 chip per boundary point for the gallery built by
 * scripts/c2_chip_assemble.py.  Two renders per point:
 *     _tc  true colour  (B4 B3 B2)          -- what the expert read
 *     _fc  false colour (B8 B4 B3)          -- vegetation = red, water = black
 *
 * Point list is generated by scripts/c2_chip_select.py
 *   (data/analysis_outputs/c2_chip_figure/points_for_gee.js) -- the block
 *   below is a copy; regenerate + repaste if N_PER_CITY changes.
 *
 * Groups:  A = C2  WC=built,  expert=non-built            (directional error)
 *          B = C1  DW=Esri=built, expert=non-built, WC dissents (coupled error)
 *          C = counter-example  WC=built, expert=built
 *
 * Imagery recipe = the BAMS selection pipeline:
 *   COPERNICUS/S2_SR_HARMONIZED, 2021, CLOUDY_PIXEL_PERCENTAGE < 20, median.
 *
 * Two ways to get the images out:
 *   1. QUICK PREVIEW  -- press "Print thumb URLs", click each link, images
 *                        open in a browser tab (right-click, Save).
 *   2. BATCH EXPORT   -- open the Tasks tab, Run every "c2_..." task.  Files
 *                        land in Google Drive / <DRIVE_FOLDER>/ as GeoTIFF
 *                        (3-band uint8, already stretched).
 * Either way, drop the files into
 *   data/analysis_outputs/c2_chip_figure/chips/
 * then run scripts/c2_chip_assemble.py.
 ******************************************************************************/

var YEAR         = 2021;
var HALF_M       = 375;     // half window width, metres  (chip is 2*HALF_M across)
var DIMENSIONS   = 600;     // output pixels per side
var DRIVE_FOLDER = 'c2_chips';

// ---- points (copy of data/analysis_outputs/c2_chip_figure/points_for_gee.js)
var PTS = [
  {pid:'A01', id:1326, city:'Wuhan', lon:114.1549868, lat:30.4209530, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A02', id:1804, city:'Wuhan', lon:114.1803193, lat:30.5486935, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A03', id:4251, city:'Hefei', lon:117.3139125, lat:31.9277871, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A04', id:2773, city:'Hefei', lon:117.3709555, lat:32.4582423, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A05', id:2863, city:'Nanchang', lon:115.9678769, lat:28.7251134, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A06', id:4930, city:'Nanchang', lon:115.9195475, lat:28.5031397, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A07', id:4904, city:'Nanjing', lon:118.6166493, lat:32.2153378, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A08', id:1929, city:'Nanjing', lon:118.6380292, lat:32.5872403, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A09', id:1831, city:'Changsha', lon:112.9855599, lat:28.1691461, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A10', id:1452, city:'Changsha', lon:113.1097969, lat:28.4196862, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A11', id:224, city:'Hangzhou', lon:118.9397874, lat:29.4639517, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'A12', id:2972, city:'Hangzhou', lon:120.1928483, lat:30.2462965, grp:'A', expert:'non-built', wc:'built', dw:'built', esri:'built'},
  {pid:'B01', id:9555, city:'Wuhan', lon:114.5998325, lat:30.7547670, grp:'B', expert:'non-built', wc:'non-built', dw:'built', esri:'built'},
  {pid:'B02', id:6115, city:'Hefei', lon:117.1705414, lat:31.6711384, grp:'B', expert:'non-built', wc:'non-built', dw:'built', esri:'built'},
  {pid:'B03', id:8454, city:'Nanchang', lon:115.9081389, lat:28.7488290, grp:'B', expert:'non-built', wc:'non-built', dw:'built', esri:'built'},
  {pid:'B04', id:5300, city:'Nanjing', lon:119.1006616, lat:31.9181751, grp:'B', expert:'non-built', wc:'non-built', dw:'built', esri:'built'},
  {pid:'B05', id:5561, city:'Changsha', lon:112.4840305, lat:28.0809315, grp:'B', expert:'non-built', wc:'non-built', dw:'built', esri:'built'},
  {pid:'B06', id:9329, city:'Hangzhou', lon:119.7421625, lat:30.2808813, grp:'B', expert:'non-built', wc:'non-built', dw:'built', esri:'built'},
  {pid:'C01', id:2183, city:'Wuhan', lon:114.7723090, lat:30.9676677, grp:'C', expert:'built', wc:'built', dw:'built', esri:'built'},
  {pid:'C02', id:3557, city:'Hefei', lon:117.5780172, lat:31.9140429, grp:'C', expert:'built', wc:'built', dw:'built', esri:'built'},
  {pid:'C03', id:1708, city:'Nanchang', lon:115.7962986, lat:28.5634167, grp:'C', expert:'built', wc:'built', dw:'built', esri:'built'},
  {pid:'C04', id:3429, city:'Nanjing', lon:118.8811133, lat:31.3277125, grp:'C', expert:'built', wc:'built', dw:'built', esri:'built'},
  {pid:'C05', id:1975, city:'Changsha', lon:113.0498793, lat:28.2658048, grp:'C', expert:'built', wc:'built', dw:'built', esri:'built'},
  {pid:'C06', id:4967, city:'Hangzhou', lon:120.2436909, lat:30.5165091, grp:'C', expert:'built', wc:'built', dw:'built', esri:'built'}
];

// ---------------------------------------------------------------------------
var V_TRUE  = {bands: ['B4', 'B3', 'B2'], min: 200, max: 2500};
var V_FALSE = {bands: ['B8', 'B4', 'B3'], min: 200, max: 4000};

function s2composite(geom) {
  return ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterBounds(geom)
    .filterDate(YEAR + '-01-01', YEAR + '-12-31')
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))
    .median();
}

function regionOf(p) {
  return ee.Geometry.Point([p.lon, p.lat]).buffer(HALF_M).bounds();
}

function rendersOf(p) {
  var region = regionOf(p);
  var s2 = s2composite(region);
  return {
    region: region,
    tc: s2.visualize(V_TRUE),
    fc: s2.visualize(V_FALSE)
  };
}

// ---- on-screen preview ----------------------------------------------------
var wc = ee.ImageCollection('ESA/WorldCover/v200').first().select('Map');
var allFc = ee.FeatureCollection(PTS.map(function (p) {
  return ee.Feature(ee.Geometry.Point([p.lon, p.lat]), p);
}));
Map.setOptions('HYBRID');
Map.addLayer(wc, {}, 'ESA WorldCover v200', false, 0.5);
Map.addLayer(allFc.style({color: 'ff0', fillColor: '00000000', pointSize: 8, width: 2}),
             {}, 'all points');
Map.centerObject(allFc, 7);

// ---- controls ----------------------------------------------------------------
function printThumbs() {
  print('==== C2 chip thumbnails  (' + PTS.length + ' points x2)  ====');
  PTS.forEach(function (p) {
    var r = rendersOf(p);
    var base = {region: r.region, dimensions: DIMENSIONS, format: 'png'};
    print(p.pid + '  ' + p.city + '  grp ' + p.grp +
          '  [WC=' + p.wc + ' DW=' + p.dw + ' Esri=' + p.esri +
          ' | expert=' + p.expert + ']');
    print('   tc: ' + r.tc.getThumbURL(base));
    print('   fc: ' + r.fc.getThumbURL(base));
  });
}

function runExports() {
  PTS.forEach(function (p) {
    var r = rendersOf(p);
    ['tc', 'fc'].forEach(function (kind) {
      Export.image.toDrive({
        image: r[kind],
        description: 'c2_' + p.pid + '_' + kind,
        folder: DRIVE_FOLDER,
        fileNamePrefix: 'c2_' + p.pid + '_' + p.id + '_' + p.city + '_' + kind,
        region: r.region,
        dimensions: DIMENSIONS,
        fileFormat: 'GeoTIFF'
      });
    });
  });
  print('Export tasks queued -- open the Tasks tab and Run each "c2_..." task.');
}

var panel = ui.Panel({style: {position: 'top-left', padding: '8px', width: '260px'}});
panel.add(ui.Label('C2 / C1 chip export', {fontWeight: 'bold'}));
panel.add(ui.Label(PTS.length + ' points  ·  ' + (2 * HALF_M) + ' m window  ·  ' +
                   DIMENSIONS + ' px', {fontSize: '12px', color: '#666'}));
panel.add(ui.Button('Print thumb URLs', printThumbs));
panel.add(ui.Button('Queue Drive exports', runExports));
panel.add(ui.Label('Then: drop files in data/analysis_outputs/c2_chip_figure/chips/ ' +
                   'and run c2_chip_assemble.py', {fontSize: '11px', color: '#888'}));
ui.root.insert(0, panel);
